// GENERAL
export const SHOW_LOGIN = 'SHOW_LOGIN';
export const INCREASE = 'INCREASE';
export const DECREASE = 'DECREASE';

// VIEW
export const LEFT_NAV_SHOWN = 'LEFT_NAV_SHOWN';
export const TOGGLE_LEFT_MENU = 'TOGGLE_LEFT_MENU';
export const CHANGE_VIEW = 'CHANGE_VIEW';
export const SET_CHARACTER_VIEW = 'SET_CHARACTER_VIEW';

// CHARACTER
export const LOAD_CHARACTERS = 'LOAD_CHARACTERS';
export const SELECT_CHARACTER = 'SELECT_CHARACTER';
export const ADD_CHARACTER = 'ADD_CHARACTER';
export const EDIT_CHARCTER = 'EDIT_CHARCTER';
export const DELETE_CHARACTER = 'DELETE_CHARACTER';
