os:
  - linux
  - osx

branches:
  only:
    - master

env:
  - NODE_VERSION="5.1.0"

script:
  - chmod +x ./scripts/travis-build.sh
  - ./scripts/travis-build.sh

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change
