var CharacterConstants = {
  FETCH_CHARACTERS: "FETCH_CHARACTERS",

  SELECT_CHARACTER: "SELECT_CHARACTER",
  REMOVE_CHARACTER: "REMOVE_CHARACTER",
  EDIT_CHARACTER: "EDIT_CHARACTER",
  VIEW_CHARACTER:" VIEW_CHARACTER",
  
  CHANGE_VIEW: "CHANGE_VIEW",

  GET_CHARACTER_LIST: "GET_CHARACTER_LIST"
};

module.exports = CharacterConstants;
