var CharacterConstants = {
  FETCH_CHARACTERS: "FETCH_CHARACTERS",
  SELECT_CHARACTER: "SELECT_CHARACTER",
  CREATE_CHARACTER:   "CREATE_CHARACTER",
  EDIT_CHARACTER:   "EDIT_CHARACTER",
  VIEW_CHARACTER:   "VIEW_CHARACTER",
  REMOVE_CHARACTER: "REMOVE_CHARACTER",
  LIST_STATE:       "LIST_STATE",
  FILTER_TEXT:       "FILTER_TEXT",
  CHANGE_VIEW: "CHANGE_VIEW",
  FETCH_VIEWS: "FETCH_VIEWS",
  SET_SELECTED_VIEW: "SET_SELECTED_VIEW",
  GET_CHARACTER_LIST: "GET_CHARACTER_LIST"
};

module.exports = CharacterConstants;
