var evConstants = {
  SHOW_LOGIN: "SHOW_LOGIN",
  CHANGE_VIEW: "CHANGE_VIEW",
  SET_CHARACTER_VIEW: "SET_CHARACTER_VIEW",
  SET_SELECTED_CHARACTER: "SET_SELECTED_CHARACTER",
};

module.exports = evConstants;
